Cargo: add ureq with platform-verifier as build dep
This works around the following compile error on ARM64:

  thread 'main' panicked at /home/staff/stijn/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ureq-3.1.4/src/tls/rustls.rs:183:17:
  Rustls + PlatformVerifier requires feature: platform-verifier

This pulls in openssl-probe, but this is 100% Rust code that does not
link against OpenSSL.

Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>